#!/usr/bin/env sh

if [ -n "$(git status --porcelain)" ]; then
  echo "There are local changes. Please clean these up before continuing."
  exit
fi
git checkout master
git pull
yarn config set version-tag-prefix "release/"
yarn config set version-git-message "[release]"
yarn version
version=$(node -e "console.log(require('./package.json').version)")
git push
git push origin --tags
